server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root
    initialSize: 20
    driverClassName: com.mysql.jdbc.Driver
  sleuth:
    enabled: false

zipkin:
  storage:
    type: mysql